== libfido2

image:https://api.travis-ci.org/Yubico/libfido2.svg?branch=master["Build Status (Travis)", link="https://travis-ci.org/Yubico/libfido2"]
image:https://ci.appveyor.com/api/projects/status/5yhnbr78gn6eraw1/branch/master?svg=true["Build Status (AppVeyor)", link="https://ci.appveyor.com/project/Yubico53275/libfido2/branch/master"]
image:https://img.shields.io/badge/license-BSD-blue.svg["License", link="https://raw.githubusercontent.com/Yubico/libfido2/master/LICENSE"]

*libfido2* provides library functionality and command-line tools to
communicate with a FIDO device over USB, and to verify attestation and
assertion signatures.

*libfido2* supports the FIDO U2F (CTAP 1) and FIDO 2.0 (CTAP 2) protocols.

For usage, see the `examples/` directory.

=== License

*libfido2* is licensed under the BSD 2-clause license.  See the _LICENSE_
file for the full license text.

=== Supported Platforms

*libfido2* is known to work on Linux, MacOS, and Windows.

=== Documentation

Documentation is available in troff and HTML formats. An
https://developers.yubico.com/libfido2/Manuals/[online mirror of *libfido2*'s documentation]
is also available.

=== Installation

==== Ubuntu

  $ sudo apt-add-repository ppa:yubico/stable
  $ sudo apt update
  $ sudo apt install libfido2-dev

Or from source, on UNIX-like systems:

  $ (rm -rf build && mkdir build && cd build && cmake ..)
  $ make -C build
  $ sudo make -C build install

Depending on the platform, the PKG_CONFIG_PATH environment variable may need to
be set.

*libfido2* depends on [hidapi](https://github.com/signal11/hidapi),
[libcbor](https://github.com/pjk/libcbor), and
[LibreSSL](https://github.com/libressl-portable/portable) (alternatively,
[OpenSSL](https://www.openssl.org) may be used).

For complete, OS-specific installation instructions, please refer to the
`.travis/` (Linux, MacOS) and `windows/` directories.

Under Linux you will need to add a Udev rule to be able to access the FIDO
device, or run as root. For example, the Udev rule may contain the following:

----
#Udev rule for allowing HID access to Yubico devices for FIDO support.

KERNEL=="hidraw*", SUBSYSTEM=="hidraw", \
  MODE="0664", GROUP="plugdev", ATTRS{idVendor}=="1050"
----
