#!/bin/bash -u
#
# Copyright (c) 2019 Yubico AB. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

T=libfido2_fuzz_assert

sync() {
	[ -d ${T} ] || mkdir ${T}
	gsutil -q -m rsync -d -r ${REMOTE}/libFuzzer/${T} ${T}
}

run() {
	build/fuzz/fuzz_assert -max_len=17408 -runs=1 ${T} 2>/dev/null 1>&2
}

case "$1" in
sync)
	sync
	;;
run)
	run
	exit 0
	;;
*)
	echo unknown command "$1"
	exit 1
esac
