#!/bin/sh -eux

${CC} --version

# Build and install libfido2.
for T in Debug Release; do
	mkdir build-$T
	(cd build-$T && cmake -DCMAKE_BUILD_TYPE=$T ..)
	make -j"$(nproc)" -C build-$T
	make -C build-$T regress
	sudo make -C build-$T install
done

# Check udev/fidodevs.
[ -x "$(which update-alternatives)" ] && {
	sudo update-alternatives --set awk "$(which original-awk)"
}
udev/check.sh udev/fidodevs
