#!/bin/sh -eux

${CC} --version
SCAN=scan-build${CC#clang}

# Check exports.
(cd src && ./diff_exports.sh)

# Build, analyze, and install libfido2.
mkdir build
(cd build && ${SCAN} --use-cc="${CC}" cmake -DCMAKE_BUILD_TYPE=Debug ..)
${SCAN} --use-cc="${CC}" --status-bugs make -j2 -C build
sudo make -C build install
