#!/bin/sh -eux

export PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)/lib/pkgconfig"
SCAN="$(brew --prefix llvm)/bin/scan-build"

# Build, analyze, and install libfido2.
for T in Debug Release; do
	mkdir build-$T
	(cd build-$T && ${SCAN} cmake -DCMAKE_BUILD_TYPE=$T ..)
	${SCAN} --status-bugs make -j"$(sysctl -n hw.ncpu)" -C build-$T
	make -C build-$T man_symlink_html
	sudo make -C build-$T install
done
