#!/bin/sh -eux

# Copyright (c) 2020 Yubico AB. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

LIBCBOR_URL="git://github.com/pjk/libcbor"
LIBCBOR_TAG="v0.8.0"
LIBCBOR_ASAN="address alignment bounds"
LIBCBOR_MSAN="memory"
OPENSSL_URL="git://github.com/openssl/openssl"
OPENSSL_TAG="OpenSSL_1_1_1h"
FIDO2_ASAN="address bounds leak pointer-compare pointer-subtract undefined"
FIDO2_MSAN="memory"
COMMON_CFLAGS="-g2 -fno-omit-frame-pointer"
UBSAN_OPTIONS="halt_on_error=1:print_stacktrace=1"
ASAN_OPTIONS="${UBSAN_OPTIONS}:detect_invalid_pointer_pairs=1:detect_leaks=1"
MSAN_OPTIONS="${UBSAN_OPTIONS}"

case "$1" in
asan)
	LIBCBOR_CFLAGS="-fsanitize=$(echo "${LIBCBOR_ASAN}" | tr ' ' ',')"
	FIDO2_CFLAGS="-fsanitize=$(echo "${FIDO2_ASAN}" | tr ' ' ',')"
	;;
msan)
	LIBCBOR_CFLAGS="-fsanitize=$(echo "${LIBCBOR_MSAN}" | tr ' ' ',')"
	FIDO2_CFLAGS="-fsanitize=$(echo "${FIDO2_MSAN}" | tr ' ' ',') -fsanitize-memory-track-origins"
	;;
*)
	echo "unknown sanitiser \"$1\"" 1>&2 && exit 1
esac

${CC} --version
WORKDIR="${WORKDIR:-$(pwd)}"
FAKEROOT="${FAKEROOT:-$(mktemp -d)}"
cd "${FAKEROOT}"

# libcbor
git clone "${LIBCBOR_URL}" -b "${LIBCBOR_TAG}"
cd libcbor
patch -p0 -s < "${WORKDIR}/fuzz/README"
mkdir build
(cd build && cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_C_FLAGS_DEBUG="${LIBCBOR_CFLAGS} ${COMMON_CFLAGS}" \
    -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_PREFIX="${FAKEROOT}" \
    -DSANITIZE=OFF ..)
make VERBOSE=1 -C build all install
cd -

# openssl
git clone "${OPENSSL_URL}" -b "${OPENSSL_TAG}"
cd openssl
./Configure linux-x86_64-clang "enable-$1" --prefix="${FAKEROOT}" \
    --openssldir="${FAKEROOT}/openssl"
make install_sw
cd -

# libfido2
mkdir build
export PKG_CONFIG_PATH="${FAKEROOT}/lib/pkgconfig"
(cd build && cmake -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_C_FLAGS_DEBUG="${FIDO2_CFLAGS} ${COMMON_CFLAGS}" -DFUZZ=ON \
    -DLIBFUZZER=ON "${WORKDIR}")
make -C build

# fuzz
mkdir corpus
curl -s https://ambientworks.net/libfido2/corpus.tgz | tar -C corpus -zxf -
export UBSAN_OPTIONS ASAN_OPTIONS MSAN_OPTIONS
for f in assert bio cred credman mgmt; do
	build/fuzz/fuzz_${f} -use_value_profile=1 -reload=30 -print_pcs=1 \
	    -print_funcs=30 -timeout=10 -runs=1 corpus/fuzz_${f}
done
