#!/bin/sh -eux

${CC} --version

# Build and install libcbor.
git clone git://github.com/pjk/libcbor
cd libcbor
git checkout v0.5.0
mkdir build
(cd build && cmake ..)
make -C build
sudo make -C build install
cd ..

# Build, analyze, and install libfido2.
mkdir build
(cd build && scan-build cmake ..)
scan-build --status-bugs make -C build
sudo make -C build install
