#!/bin/sh -eux

${CC} --version

# Check exports.
(cd src && ./diff_exports.sh)

# Build, analyze, and install libfido2.
mkdir build
(cd build && scan-build-9 cmake -DCMAKE_BUILD_TYPE=Debug ..)
scan-build-9 --status-bugs make -C build
sudo make -C build install
