#!/bin/sh -eux

${CC} --version

# Build and install libcbor.
git clone git://github.com/pjk/libcbor
cd libcbor
git checkout v0.5.0
mkdir build
(cd build && cmake ..)
make -C build
sudo make -C build install
cd ..

# Build and install OpenSSL 1.1.0h.
git clone git://github.com/openssl/openssl
cd openssl
git checkout OpenSSL_1_1_0h
./Configure linux-x86_64-clang
make
sudo make install_sw
cd ..

# Build and install libfido2.
mkdir build
(cd build && cmake ..)
make -C build
sudo make -C build install
