#!/bin/sh -eux

${CC} --version

# Build and install libcbor.
git clone git://github.com/pjk/libcbor
cd libcbor
git checkout v0.5.0
mkdir build
(cd build && cmake ..)
make -C build
sudo make -C build install
cd ..

# Prepare the ground for Homebrew.
sudo mkdir /usr/local/sbin
sudo chmod 775 /usr/local/sbin
sudo chown travis:admin /usr/local/sbin

# Install OpenSSL 1.1.1, hidapi, and mandoc from Homebrew.
brew update
brew upgrade openssl@1.1
brew switch openssl@1.1 1.1.1b
brew install hidapi
brew install mandoc

# Build and install libfido2.
export PKG_CONFIG_PATH=/usr/local/opt/openssl@1.1/lib/pkgconfig
mkdir build
(cd build && cmake -DCMAKE_BUILD_TYPE=Debug ..)
make -C build
make -C build man_symlink_html
sudo make -C build install
