name: cygwin

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - '*-ci'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022 ]
        arch: [ x64 ]
        config: [ "Debug", "Release" ]
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        .\windows\cygwin.ps1 -Config ${{ matrix.config }}
