name: fuzzer

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - '*-ci'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        cc: [ clang-12 ]
        sanitizer: [ asan, msan ]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      env:
        CC: ${{ matrix.cc }}
      run: |
        sudo apt -q update
        sudo apt install -q -y libudev-dev ${CC%-*}-tools-${CC#clang-}
        sudo apt install -q -y libpcsclite-dev
    - name: fuzz
      env:
        CC: ${{ matrix.cc }}
        SANITIZER: ${{ matrix.sanitizer }}
      run: ./.actions/fuzz-linux ${SANITIZER}
