name: fuzzer

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - '*-ci'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        cc: [ clang-14 ]
        sanitizer: [ asan, msan ]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        sudo apt -q update
        sudo apt install -q -y libudev-dev libpcsclite-dev
    - name: compiler
      env:
        CC: ${{ matrix.cc }}
      run: |
        sudo ./.actions/setup_clang "${CC}"
    - name: fuzz
      env:
        CC: ${{ matrix.cc }}
        SANITIZER: ${{ matrix.sanitizer }}
      run: ./.actions/fuzz-linux "${SANITIZER}"
