# Copyright (c) 2022-2024 Yubico AB. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
# SPDX-License-Identifier: BSD-2-Clause

name: openssl

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - '*-ci'

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc-13, clang-20, i686-w64-mingw32-gcc-11]
        openssl_version: [openssl-3.0.16, openssl-4.0.0-beta1]
    steps:
    - uses: actions/checkout@v6
    - name: dependencies
      env:
        CC: ${{ matrix.cc }}
      run: |
        sudo apt -q update
        sudo apt install -q -y libcbor-dev libudev-dev libz-dev \
          original-awk mandoc libpcsclite-dev
        sudo apt remove -y libssl-dev
        if [ "${CC%-*}" == "clang" ]; then
          sudo ./.actions/setup_clang "${CC}"
        elif [ "${CC%-*}" == "i686-w64-mingw32-gcc" ]; then
          sudo apt install -q -y binutils-mingw-w64-i686 gcc-mingw-w64 \
           g++-mingw-w64 mingw-w64-i686-dev
        else
          sudo apt install -q -y "${CC}"
        fi
    - name: build
      env:
        CC: ${{ matrix.cc }}
        OPENSSL_VERSION: ${{ matrix.openssl_version }}
      run: ./.actions/build-linux-openssl-${CC%-*}
