name: windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: .\windows\build.ps1

    - uses: nevun/action-checksec@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_COMMENT_URL: ${{ github.event.pull_request.comments_url }}
      with:
        executables: |
          "output/64/bin/fido2-cred.exe"
          "output/64/bin/fido2-assert.exe"
          "output/64/bin/fido2-token.exe"
          "output/32/bin/fido2-cred.exe"
          "output/32/bin/fido2-assert.exe"
          "output/32/bin/fido2-token.exe"
        libraries: |
          "output/64/lib/fido2.dll"
          "output/32/lib/fido2.dll"
        print_flag_table: "on"
