name: windows

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    - '*-ci'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2019, windows-2022 ]
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: .\windows\build.ps1 -WinSDK '10.0.19041.0' -Fido2Flags '/analyze'
